// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/main/jflex/lexer.jflex

/* JFlex example: partial Java language lexer specification */
package com.navidad;
import java_cup.runtime.*;
import java.util.ArrayList;
import java.util.List;
import java.io.IOException;



@SuppressWarnings("fallthrough")
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\1\1\5"+
    "\1\6\1\7\3\0\1\10\1\11\1\12\1\13\1\14"+
    "\1\0\1\15\1\16\1\17\1\20\11\21\2\0\1\22"+
    "\1\23\1\24\1\0\1\25\32\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\0\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\26\1\45\1\46\1\47"+
    "\1\50\1\51\1\52\1\26\1\53\1\54\1\55\1\56"+
    "\5\26\1\57\1\60\1\61\1\62\6\0\1\3\u01a2\0"+
    "\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\0\1\2\3\1\1\3\1\4\1\5\1\2"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\2\14\1\15"+
    "\1\2\1\16\1\1\1\17\1\20\1\21\1\22\1\23"+
    "\15\17\1\24\1\25\1\26\1\27\1\30\1\31\2\0"+
    "\1\32\1\33\1\34\1\35\2\0\1\36\1\0\1\37"+
    "\1\40\1\41\1\42\4\17\1\43\4\17\1\44\7\17"+
    "\1\45\1\46\1\0\1\47\1\50\1\51\1\52\1\53"+
    "\7\17\1\54\1\55\7\17\1\56\1\17\1\57\1\60"+
    "\1\61\2\17\1\62\1\17\1\63\2\17\1\64\1\17"+
    "\1\65\1\66\1\67\1\70\2\17\1\71\1\72\1\73";

  private static int [] zzUnpackAction() {
    int [] result = new int[124];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\63\0\146\0\231\0\146\0\314\0\377\0\146"+
    "\0\146\0\u0132\0\146\0\146\0\u0165\0\u0198\0\u01cb\0\u01fe"+
    "\0\u0231\0\u0264\0\u0297\0\u02ca\0\146\0\u02fd\0\u0330\0\146"+
    "\0\u0363\0\146\0\146\0\u0396\0\u03c9\0\u03fc\0\u042f\0\u0462"+
    "\0\u0495\0\u04c8\0\u04fb\0\u052e\0\u0561\0\u0594\0\u05c7\0\u05fa"+
    "\0\146\0\146\0\146\0\146\0\146\0\146\0\u062d\0\u0660"+
    "\0\146\0\146\0\146\0\146\0\u0693\0\u06c6\0\146\0\u06f9"+
    "\0\146\0\146\0\146\0\146\0\u072c\0\u075f\0\u0792\0\u07c5"+
    "\0\u0330\0\u07f8\0\u082b\0\u085e\0\u0891\0\u0330\0\u08c4\0\u08f7"+
    "\0\u092a\0\u095d\0\u0990\0\u09c3\0\u09f6\0\146\0\146\0\u0a29"+
    "\0\u06c6\0\146\0\146\0\146\0\u0330\0\u0a5c\0\u0a8f\0\u0ac2"+
    "\0\u0af5\0\u0b28\0\u0b5b\0\u0b8e\0\u0330\0\u0330\0\u0bc1\0\u0bf4"+
    "\0\u0c27\0\u0c5a\0\u0c8d\0\u0cc0\0\u0cf3\0\u0330\0\u0d26\0\u0330"+
    "\0\u0330\0\u0330\0\u0d59\0\u0d8c\0\u0330\0\u0dbf\0\u0330\0\u0df2"+
    "\0\u0e25\0\u0330\0\u0e58\0\u0330\0\u0330\0\u0330\0\u0330\0\u0e8b"+
    "\0\u0ebe\0\u0330\0\u0330\0\u0330";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[124];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\3\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\3\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\3\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\2\27\1\42\2\27\1\43\2\27\1\44"+
    "\1\45\1\46\1\47\1\50\1\51\1\52\1\53\1\54"+
    "\2\3\1\55\1\3\1\55\1\3\1\56\21\3\1\31"+
    "\32\3\64\0\1\4\63\0\1\5\103\0\1\57\37\0"+
    "\2\60\3\0\56\60\13\0\1\61\63\0\1\62\63\0"+
    "\1\63\3\0\1\22\60\0\1\64\13\0\1\65\45\0"+
    "\1\66\62\0\1\66\1\0\2\22\64\0\1\67\62\0"+
    "\1\70\37\0\2\26\1\5\1\0\1\6\56\26\20\0"+
    "\2\27\4\0\1\27\5\0\23\27\12\0\1\71\41\0"+
    "\1\72\2\0\1\73\1\0\1\74\25\0\2\27\4\0"+
    "\1\27\5\0\17\27\1\75\3\27\24\0\2\27\4\0"+
    "\1\27\5\0\15\27\1\76\1\27\1\77\3\27\24\0"+
    "\2\27\4\0\1\27\5\0\7\27\1\100\13\27\24\0"+
    "\2\27\4\0\1\27\5\0\15\27\1\101\5\27\24\0"+
    "\2\27\4\0\1\27\5\0\12\27\1\102\10\27\24\0"+
    "\2\27\4\0\1\27\5\0\1\103\11\27\1\104\2\27"+
    "\1\105\5\27\24\0\2\27\4\0\1\27\5\0\5\27"+
    "\1\106\6\27\1\107\6\27\24\0\2\27\4\0\1\27"+
    "\5\0\1\110\22\27\24\0\2\27\4\0\1\27\5\0"+
    "\17\27\1\111\3\27\24\0\2\27\4\0\1\27\5\0"+
    "\4\27\1\112\16\27\24\0\2\27\4\0\1\27\5\0"+
    "\21\27\1\113\1\27\24\0\2\27\4\0\1\27\5\0"+
    "\17\27\1\114\3\27\24\0\2\27\4\0\1\27\5\0"+
    "\14\27\1\115\6\27\27\0\1\116\47\0\1\117\52\0"+
    "\33\65\1\120\27\65\20\0\2\121\63\0\1\122\1\123"+
    "\1\124\56\0\2\27\4\0\1\27\5\0\17\27\1\125"+
    "\3\27\24\0\2\27\4\0\1\27\5\0\15\27\1\126"+
    "\5\27\24\0\2\27\4\0\1\27\5\0\4\27\1\127"+
    "\16\27\24\0\2\27\4\0\1\27\5\0\1\130\22\27"+
    "\24\0\2\27\4\0\1\27\5\0\10\27\1\131\7\27"+
    "\1\132\2\27\24\0\2\27\4\0\1\27\5\0\12\27"+
    "\1\133\10\27\24\0\2\27\4\0\1\27\5\0\15\27"+
    "\1\134\5\27\24\0\2\27\4\0\1\27\5\0\17\27"+
    "\1\135\3\27\24\0\2\27\4\0\1\27\5\0\21\27"+
    "\1\136\1\27\24\0\2\27\4\0\1\27\5\0\10\27"+
    "\1\137\12\27\24\0\2\27\4\0\1\27\5\0\10\27"+
    "\1\140\12\27\24\0\2\27\4\0\1\27\5\0\1\141"+
    "\20\27\1\142\1\27\24\0\2\27\4\0\1\27\5\0"+
    "\17\27\1\143\3\27\24\0\2\27\4\0\1\27\5\0"+
    "\22\27\1\144\24\0\2\27\4\0\1\27\5\0\21\27"+
    "\1\145\1\27\23\0\1\5\63\0\2\27\4\0\1\27"+
    "\5\0\12\27\1\146\10\27\24\0\2\27\4\0\1\27"+
    "\5\0\1\147\22\27\24\0\2\27\4\0\1\27\5\0"+
    "\17\27\1\150\3\27\24\0\2\27\4\0\1\27\5\0"+
    "\5\27\1\151\15\27\24\0\2\27\4\0\1\27\5\0"+
    "\4\27\1\152\16\27\24\0\2\27\4\0\1\27\5\0"+
    "\20\27\1\153\2\27\24\0\2\27\4\0\1\27\5\0"+
    "\1\154\22\27\24\0\2\27\4\0\1\27\5\0\14\27"+
    "\1\155\6\27\24\0\2\27\4\0\1\27\5\0\14\27"+
    "\1\156\6\27\24\0\2\27\4\0\1\27\5\0\3\27"+
    "\1\157\17\27\24\0\2\27\4\0\1\27\5\0\22\27"+
    "\1\160\24\0\2\27\4\0\1\27\5\0\10\27\1\161"+
    "\12\27\24\0\2\27\4\0\1\27\5\0\4\27\1\162"+
    "\16\27\24\0\2\27\4\0\1\27\5\0\10\27\1\163"+
    "\12\27\24\0\2\27\4\0\1\27\5\0\11\27\1\164"+
    "\11\27\24\0\2\27\4\0\1\27\5\0\4\27\1\165"+
    "\16\27\24\0\2\27\4\0\1\27\5\0\21\27\1\166"+
    "\1\27\24\0\2\27\4\0\1\27\5\0\21\27\1\167"+
    "\1\27\24\0\2\27\4\0\1\27\5\0\17\27\1\170"+
    "\3\27\24\0\2\27\4\0\1\27\5\0\14\27\1\171"+
    "\6\27\24\0\2\27\4\0\1\27\5\0\12\27\1\172"+
    "\10\27\24\0\2\27\4\0\1\27\5\0\14\27\1\173"+
    "\6\27\24\0\2\27\4\0\1\27\5\0\6\27\1\174"+
    "\14\27\4\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[3825];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\0\1\11\1\1\1\11\2\1\2\11\1\1"+
    "\2\11\10\1\1\11\2\1\1\11\1\1\2\11\15\1"+
    "\6\11\2\0\4\11\2\0\1\11\1\0\4\11\21\1"+
    "\2\11\1\0\1\1\3\11\50\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[124];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    StringBuffer string = new StringBuffer();


    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    //Debo de utilizar a este metodo para poder obtener el valor de los tokens
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }

    public List<Symbol> getTokens() {
        List<Symbol> tokens = new ArrayList<Symbol>();
        Symbol token;
        try {
            while ((token = next_token()).sym != sym.EOF) {
                if (token.sym == sym.MEDIAS_ERROR) {
                    Symbol error = symbol(token.sym, token.value);
                    System.err.println(sym.terminalNames[error.sym]+ " "   + error.value + " en la linea " + error.left + " y columna " + error.right);
                } else {
                    tokens.add(symbol(token.sym, token.value));
                }

            }
        } catch (IOException e) {
            System.err.println("Error: " + e.getMessage());
        }
        return tokens;
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { /* ignore */
            }
          // fall through
          case 60: break;
          case 2:
            { string.append(yytext());
            }
          // fall through
          case 61: break;
          case 3:
            { return new Symbol(sym.REY_BALTASAR_NOT, yytext());
            }
          // fall through
          case 62: break;
          case 4:
            { string.setLength(0); yybegin(STRING);
            }
          // fall through
          case 63: break;
          case 5:
            { return new Symbol(sym.REY_GASPAR_DISJUNCTION, yytext());
            }
          // fall through
          case 64: break;
          case 6:
            { return new Symbol(sym.ABRE_CUENTO, yytext());
            }
          // fall through
          case 65: break;
          case 7:
            { return new Symbol(sym.CIERRE_CUENTO, yytext());
            }
          // fall through
          case 66: break;
          case 8:
            { return new Symbol(sym.COMETA_PRODUCT, yytext());
            }
          // fall through
          case 67: break;
          case 9:
            { return new Symbol(sym.RODOLFO_SUM, yytext());
            }
          // fall through
          case 68: break;
          case 10:
            { return new Symbol(sym.TRUENO_DECREASE, yytext());
            }
          // fall through
          case 69: break;
          case 11:
            { return new Symbol(sym.RAYO_FLOAT_DIVISION, yytext());
            }
          // fall through
          case 70: break;
          case 12:
            { return new Symbol(sym.L_COLACHO_INT, yytext());
            }
          // fall through
          case 71: break;
          case 13:
            { return new Symbol(sym.ELFO_LESS, yytext());
            }
          // fall through
          case 72: break;
          case 14:
            { return new Symbol(sym.ELFO_GREATER, yytext());
            }
          // fall through
          case 73: break;
          case 15:
            { return new Symbol(sym.PERSONA, yytext());
            }
          // fall through
          case 74: break;
          case 16:
            { return new Symbol(sym.ABRE_EMPAQUE, yytext());
            }
          // fall through
          case 75: break;
          case 17:
            { string.append("\\");
            }
          // fall through
          case 76: break;
          case 18:
            { return new Symbol(sym.CIERRA_EMPAQUE, yytext());
            }
          // fall through
          case 77: break;
          case 19:
            { return new Symbol(sym.REY_MELCHOR_COJUNCTION, yytext());
            }
          // fall through
          case 78: break;
          case 20:
            { return new Symbol(sym.ABRE_REGALO, yytext());
            }
          // fall through
          case 79: break;
          case 21:
            { return new Symbol(sym.FIN_REGALO, yytext());
            }
          // fall through
          case 80: break;
          case 22:
            { return new Symbol(sym.CIERRA_REGALO, yytext());
            }
          // fall through
          case 81: break;
          case 23:
            { return new Symbol(sym.CUPIDO_MODULE, yytext());
            }
          // fall through
          case 82: break;
          case 24:
            { // Acción a tomar para cualquier caracter no reconocido
    return new Symbol(sym.MEDIAS_ERROR, yytext());
            }
          // fall through
          case 83: break;
          case 25:
            { yybegin(YYINITIAL); return symbol(sym.L_SANTA_STRING, string.toString());
            }
          // fall through
          case 84: break;
          case 26:
            { return new Symbol(sym.SALTARIN_ELEVATE, yytext());
            }
          // fall through
          case 85: break;
          case 27:
            { return new Symbol(sym.QUIEN_INCREMENT, yytext());
            }
          // fall through
          case 86: break;
          case 28:
            { return new Symbol(sym.GRINCH_DECREMENT, yytext());
            }
          // fall through
          case 87: break;
          case 29:
            { return new Symbol(sym.RELAMPAGO_INT_DIVISION, yytext());
            }
          // fall through
          case 88: break;
          case 30:
            { return new Symbol(sym.ENTREGA, yytext());
            }
          // fall through
          case 89: break;
          case 31:
            { string.append("\"");
            }
          // fall through
          case 90: break;
          case 32:
            { string.append("\n");
            }
          // fall through
          case 91: break;
          case 33:
            { string.append("\r");
            }
          // fall through
          case 92: break;
          case 34:
            { string.append("\t");
            }
          // fall through
          case 93: break;
          case 35:
            { return new Symbol(sym.HACE_DO, "do");
            }
          // fall through
          case 94: break;
          case 36:
            { return new Symbol(sym.ELFO_IF, "if");
            }
          // fall through
          case 95: break;
          case 37:
            { return new Symbol(sym.ELFO_NOT_EQUAL, yytext());
            }
          // fall through
          case 96: break;
          case 38:
            { return new Symbol(sym.L_CLAUS_CHAR, yytext());
            }
          // fall through
          case 97: break;
          case 39:
            { return new Symbol(sym.L_JOULUPUKKI_FLOAT, yytext());
            }
          // fall through
          case 98: break;
          case 40:
            { return new Symbol(sym.ELFO_LESS_EQUAL, yytext());
            }
          // fall through
          case 99: break;
          case 41:
            { return new Symbol(sym.ELFO_EQUAL, yytext());
            }
          // fall through
          case 100: break;
          case 42:
            { return new Symbol(sym.ELFO_GREATER_EQUAL, yytext());
            }
          // fall through
          case 101: break;
          case 43:
            { return new Symbol(sym.VIEJITO_PASCUERO_ARRAY, "arr");
            }
          // fall through
          case 102: break;
          case 44:
            { return new Symbol(sym.ENVUELVE_FOR, "for");
            }
          // fall through
          case 103: break;
          case 45:
            { return new Symbol(sym.COLACHO_INT, "int");
            }
          // fall through
          case 104: break;
          case 46:
            { return new Symbol(sym.PAPA_NOEL_BOOLEAN, "bool");
            }
          // fall through
          case 105: break;
          case 47:
            { return new Symbol(sym.CLAUS_CHAR, "char");
            }
          // fall through
          case 106: break;
          case 48:
            { return new Symbol(sym.HADA_ELIF, "elif");
            }
          // fall through
          case 107: break;
          case 49:
            { return new Symbol(sym.DUENDE_ELSE, "else");
            }
          // fall through
          case 108: break;
          case 50:
            { return new Symbol(sym.ESTRELLA_MAIN, "main");
            }
          // fall through
          case 109: break;
          case 51:
            { return new Symbol(sym.ESCUCHA_READ, "read");
            }
          // fall through
          case 110: break;
          case 52:
            { return new Symbol(sym.PAPA_NOEL_TRUE, "true");
            }
          // fall through
          case 111: break;
          case 53:
            { return new Symbol(sym.CORTA_BREAK, "break");
            }
          // fall through
          case 112: break;
          case 54:
            { return new Symbol(sym.PAPA_NOEL_FALSE, "false");
            }
          // fall through
          case 113: break;
          case 55:
            { return new Symbol(sym.JOULUPUKKI_FLOAT, "float");
            }
          // fall through
          case 114: break;
          case 56:
            { return new Symbol(sym.NARRA_PRINT, "print");
            }
          // fall through
          case 115: break;
          case 57:
            { return new Symbol(sym.REVISA_UNTIL, "until");
            }
          // fall through
          case 116: break;
          case 58:
            { return new Symbol(sym.ENVIA_RETURN, "return");
            }
          // fall through
          case 117: break;
          case 59:
            { return new Symbol(sym.SANTA_STRING, "string");
            }
          // fall through
          case 118: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
