
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.navidad;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int ABRE_CUENTO = 28;
  public static final int REY_MELCHOR = 18;
  public static final int CIERRA_EMPAQUE = 31;
  public static final int ABRE_REGALO = 32;
  public static final int ELFO_MAYOR = 12;
  public static final int CIERRA_REGALO = 33;
  public static final int HADA = 35;
  public static final int PERSONA = 9;
  public static final int ELFO_MAYOR_IGUAL = 16;
  public static final int CARBON = 47;
  public static final int DUENDE = 36;
  public static final int REY_GASPAR = 19;
  public static final int SEPARADOR = 46;
  public static final int L_JOULUPUKKI = 27;
  public static final int ENTREGA = 45;
  public static final int RAYO = 5;
  public static final int RODOLFO = 2;
  public static final int RELAMPAGO = 4;
  public static final int ELFO_MENOR_IGUAL = 17;
  public static final int NAVIDAD = 23;
  public static final int FIN_REGALO = 44;
  public static final int NARRA = 42;
  public static final int CIERRE_CUENTO = 29;
  public static final int ELFO_NO_IGUAL = 15;
  public static final int HACE = 38;
  public static final int SALTARIN = 6;
  public static final int ENVUELVE = 37;
  public static final int COMETA = 7;
  public static final int BOOLEAN = 49;
  public static final int GRINCH = 10;
  public static final int FESTIVAL = 24;
  public static final int EOF = 0;
  public static final int CORTA = 41;
  public static final int REVISA = 39;
  public static final int error = 1;
  public static final int TRUENO = 3;
  public static final int ABRE_EMPAQUE = 30;
  public static final int BREAK = 48;
  public static final int ESCUCHA = 43;
  public static final int CUPIDO = 8;
  public static final int ENVIA = 40;
  public static final int ELFO_IGUAL = 14;
  public static final int COLACHO = 21;
  public static final int FIESTA = 25;
  public static final int L_VIEJITO_PASCUERO = 26;
  public static final int REY_BALTASAR = 20;
  public static final int SANTA = 22;
  public static final int ELFO = 34;
  public static final int QUIEN = 11;
  public static final int ELFO_MENOR = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RODOLFO",
  "TRUENO",
  "RELAMPAGO",
  "RAYO",
  "SALTARIN",
  "COMETA",
  "CUPIDO",
  "PERSONA",
  "GRINCH",
  "QUIEN",
  "ELFO_MAYOR",
  "ELFO_MENOR",
  "ELFO_IGUAL",
  "ELFO_NO_IGUAL",
  "ELFO_MAYOR_IGUAL",
  "ELFO_MENOR_IGUAL",
  "REY_MELCHOR",
  "REY_GASPAR",
  "REY_BALTASAR",
  "COLACHO",
  "SANTA",
  "NAVIDAD",
  "FESTIVAL",
  "FIESTA",
  "L_VIEJITO_PASCUERO",
  "L_JOULUPUKKI",
  "ABRE_CUENTO",
  "CIERRE_CUENTO",
  "ABRE_EMPAQUE",
  "CIERRA_EMPAQUE",
  "ABRE_REGALO",
  "CIERRA_REGALO",
  "ELFO",
  "HADA",
  "DUENDE",
  "ENVUELVE",
  "HACE",
  "REVISA",
  "ENVIA",
  "CORTA",
  "NARRA",
  "ESCUCHA",
  "FIN_REGALO",
  "ENTREGA",
  "SEPARADOR",
  "CARBON",
  "BREAK",
  "BOOLEAN"
  };
}

